@ENDPOINT={{APPLICATION_BACKEND}}/v1/users
@id=

PATCH {{ENDPOINT}}/{{id}}
Content-Type: application/json

{
    "name": "João da Silva Atualizado",
    "email": "joao.silva@example.com",
    "phone": "11999999999",
    "cpf": "11144477735",
    "cnpj": "11222333000181",
    "password": "Senha@123"
}
